# Netlify Configuration for LogiFin Frontend

[build]
  # Frontend-only build command
  command = "npm run build:frontend"

  # Output directory (Vite builds to dist/)
  publish = "dist"

  # Netlify Functions directory
  functions = "netlify/functions"

  # Environment variables for build
  [build.environment]
    NODE_VERSION = "20"
    # Use Netlify Function as API proxy
    VITE_API_URL = "/.netlify/functions/api-proxy/api"

# SPA redirect rules - send all routes to index.html (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment specific settings
[context.production]
  [context.production.environment]
    VITE_API_URL = "/.netlify/functions/api-proxy/api"

# Deploy preview environment (for pull requests)
[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_API_URL = "/.netlify/functions/api-proxy/api"

# Branch deploy environment
[context.branch-deploy]
  [context.branch-deploy.environment]
    VITE_API_URL = "/.netlify/functions/api-proxy/api"
