# Netlify Configuration for LogiFin Frontend

[build]
  # Frontend-only build command
  command = "npm run build:frontend"

  # Output directory (Vite builds to dist/)
  publish = "dist"

  # Environment variables for build
  [build.environment]
    NODE_VERSION = "20"
    VITE_API_URL = "/api"

# API Proxy - Forward /api/* requests to backend server
[[redirects]]
  from = "/api/*"
  to = "http://34.127.125.215:4000/api/:splat"
  status = 200
  force = true

# SPA redirect rules - send all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment specific settings
[context.production]
  [context.production.environment]
    VITE_API_URL = "/api"

# Deploy preview environment (for pull requests)
[context.deploy-preview]
  [context.deploy-preview.environment]
    VITE_API_URL = "/api"

# Branch deploy environment
[context.branch-deploy]
  [context.branch-deploy.environment]
    VITE_API_URL = "/api"
